server:
  port: 8000
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      global-cors:
        cors-configurations:
          '[/**]':
            allowed-origins: '*'
            allowed-methods: '*'
      mvc:
        routes:
          - id: product-service-route
            uri: http://backend:8080
            predicates:
              - Path=/api/products/**
